// Curated source inventory built from the user's Notion "심리상담 가이드" export
// and Threads archive. This file preserves the content-migration decisions separately
// from the public GUIDE/TOOLS records so later imports can be traced and reviewed.

export type ArchiveSeedKind = "guide" | "tool";
export type ArchiveSeedStatus = "publish" | "merge" | "expand" | "review";

export type ArchiveSeedItem = {
  kind: ArchiveSeedKind;
  slug: string;
  title: string;
  source: "notion-guide" | "threads" | "both";
  status: ArchiveSeedStatus;
  category: string;
  topics: string[];
  rationale: string;
};

export const archiveSeedItems: ArchiveSeedItem[] = [
  {
    kind: "guide",
    slug: "how-to-start-therapy",
    title: "심리상담, 무엇부터 시작하면 될까요?",
    source: "both",
    status: "publish",
    category: "상담 시작하기",
    topics: ["상담 시작", "상담 준비", "상담 형태", "상담 목표"],
    rationale: "Notion의 상담 전 준비 체크리스트와 Threads의 '심리상담 어떻게 받아?' 질문을 하나의 시작 가이드로 통합합니다.",
  },
  {
    kind: "guide",
    slug: "choosing-a-therapist-credentials",
    title: "상담자를 고를 때 자격보다 함께 확인할 것들",
    source: "both",
    status: "merge",
    category: "상담 시작하기",
    topics: ["상담자 선택", "자격", "수련", "전문성", "상담 관계"],
    rationale: "Notion의 상담사 선택 체크포인트와 Threads의 자격·전문성 관련 반복 글을 통합합니다. 특정 자격을 단순 서열화하기보다 전공·수련·윤리·전문분야·관계 적합성을 함께 보도록 구성합니다.",
  },
  {
    kind: "guide",
    slug: "when-therapy-feels-uncomfortable",
    title: "상담이 불편하거나 힘들 때 해볼 수 있는 것",
    source: "both",
    status: "publish",
    category: "상담 잘 이용하기",
    topics: ["상담 관계", "불편함", "피드백", "치료적 관계", "상담 중단"],
    rationale: "Notion의 상담 중 맞지 않을 때 단계와 Threads의 '상담에서 힘이 들 때, 불편할 때' 글이 거의 직접 대응합니다.",
  },
  {
    kind: "guide",
    slug: "what-change-in-therapy-can-look-like",
    title: "좋은 상담에서 변화는 어떻게 나타날까요?",
    source: "notion-guide",
    status: "publish",
    category: "상담 잘 이용하기",
    topics: ["상담 효과", "변화", "관계", "자기이해", "종결"],
    rationale: "허니문 기간, 관계 재정렬, 상실감·혼란, 자기이해와 실제 삶의 변화까지 한 흐름으로 정리할 수 있습니다.",
  },
  {
    kind: "guide",
    slug: "attachment-is-more-than-a-type",
    title: "애착은 한 가지 유형으로만 설명되지 않습니다",
    source: "both",
    status: "publish",
    category: "마음 이해하기",
    topics: ["애착", "안정애착", "불안정애착", "관계", "민감성"],
    rationale: "Notion의 애착 요약과 Threads의 '좋은 애착은 붙고 떨어질 수 있는 것', 민감성 관련 글을 통합합니다.",
  },
  {
    kind: "guide",
    slug: "attachment-trauma-differences",
    title: "애착 트라우마·애착 손상·불안정애착·발달 트라우마는 어떻게 다를까요?",
    source: "threads",
    status: "expand",
    category: "마음 이해하기",
    topics: ["애착 트라우마", "애착 손상", "불안정애착", "발달 트라우마"],
    rationale: "Threads에 명시적으로 네 개념을 구분한 글이 있어 GUIDE로 확장 가치가 높습니다. 공개 전 학술 출처 보강이 필요한 항목입니다.",
  },
  {
    kind: "guide",
    slug: "body-and-trauma-responses",
    title: "머리는 괜찮은데 몸은 왜 계속 반응할까요?",
    source: "both",
    status: "publish",
    category: "심리치료 알아보기",
    topics: ["트라우마", "신체감각", "신경계", "SP", "안정화"],
    rationale: "Notion의 트라우마·몸 신호 설명과 Threads의 SP·신체 기반 접근, 펜듈레이션/타이테이션 글을 묶습니다.",
  },
  {
    kind: "guide",
    slug: "stabilization-does-not-fit-everyone",
    title: "심호흡과 그라운딩이 나에게 안 맞을 수도 있습니다",
    source: "both",
    status: "publish",
    category: "심리치료 알아보기",
    topics: ["안정화", "그라운딩", "호흡", "트라우마", "자기조절"],
    rationale: "Notion의 '안정화 기법이 오히려 힘들 수 있다'는 설명과 Threads의 구체적 안정화 글을 연결합니다.",
  },
  {
    kind: "guide",
    slug: "online-therapy-tips",
    title: "비대면 상담을 더 잘 이용하는 방법",
    source: "notion-guide",
    status: "publish",
    category: "상담 잘 이용하기",
    topics: ["비대면 상담", "화상상담", "전화상담", "채팅상담"],
    rationale: "화상·전화·채팅의 특성을 구분한 실용 정보로 독립 GUIDE에 적합합니다.",
  },
  {
    kind: "guide",
    slug: "ai-and-therapy-boundaries",
    title: "AI를 심리상담과 함께 사용할 때 기억할 것",
    source: "both",
    status: "expand",
    category: "상담 잘 이용하기",
    topics: ["AI", "심리상담", "맥락", "편향", "트라우마"],
    rationale: "Notion의 AI 주의사항과 Threads에서 반복된 '맥락을 모르는 AI' 관점을 통합합니다. 빠르게 변하는 영역이므로 공개 시점에 별도 최신 검토가 필요합니다.",
  },
  {
    kind: "guide",
    slug: "child-centered-limit-setting",
    title: "아이의 감정은 인정하고 한계는 분명하게: ACT 제한설정",
    source: "threads",
    status: "publish",
    category: "마음 이해하기",
    topics: ["놀이치료", "양육", "제한설정", "감정 인정", "대안 행동"],
    rationale: "Threads의 Acknowledge–Communicate–Target 설명을 부모가 바로 이해할 수 있는 GUIDE로 전환합니다.",
  },
  {
    kind: "tool",
    slug: "therapy-prep-checklist",
    title: "첫 상담 준비 체크리스트",
    source: "notion-guide",
    status: "publish",
    category: "상담",
    topics: ["첫 상담", "상담 준비", "목표", "현실적 조건"],
    rationale: "Notion에 이미 체크리스트 형태로 존재하여 TOOLS로 바로 전환하기 좋습니다.",
  },
  {
    kind: "tool",
    slug: "therapy-discomfort-note",
    title: "상담에서 불편했던 순간 정리하기",
    source: "both",
    status: "publish",
    category: "상담",
    topics: ["상담 관계", "불편함", "피드백", "경계"],
    rationale: "불편했던 지점·말·행동을 정리하고 상담자 반응을 관찰하도록 돕는 기록 도구입니다.",
  },
  {
    kind: "tool",
    slug: "information-anxiety-reset",
    title: "정보를 찾을수록 불안해질 때 중심 잡기",
    source: "threads",
    status: "publish",
    category: "자기돌봄",
    topics: ["불안", "정보 과부하", "알고리즘", "중심잡기", "자기조절"],
    rationale: "Threads의 가스라이팅·선동 상황에서의 중심잡기 글을 일반적인 정보 불안 self-care tool로 재구성합니다.",
  },
  {
    kind: "tool",
    slug: "one-bite-regulation",
    title: "힘든 감정을 한입거리로 다루기",
    source: "threads",
    status: "publish",
    category: "자기돌봄",
    topics: ["펜듈레이션", "타이테이션", "트라우마", "감정", "자기조절"],
    rationale: "괜찮은 상태와 힘든 상태를 오가고, 감당 가능한 만큼만 다루는 원리를 자기돌봄용으로 축약합니다.",
  },
  {
    kind: "tool",
    slug: "safe-place-builder",
    title: "나만의 안식처 이미지 만들기",
    source: "threads",
    status: "publish",
    category: "자기돌봄",
    topics: ["안정화", "이미지", "안식처", "감각", "자원"],
    rationale: "Threads의 '나만의 안식처를 시각화해보기' 아이디어를 직접 실행 가능한 guided prompt로 만듭니다.",
  },
  {
    kind: "tool",
    slug: "exhale-reset",
    title: "숨이 가빠질 때: 들이쉬기보다 먼저 내쉬기",
    source: "threads",
    status: "review",
    category: "자기돌봄",
    topics: ["호흡", "불안", "신체반응", "안정화"],
    rationale: "Threads의 안정화 기법 글에서 가져왔습니다. 건강·공황 관련 오해를 피하도록 공개 전 문구와 안전 안내를 별도 검토합니다.",
  },
  {
    kind: "tool",
    slug: "relationship-distance-question",
    title: "이 사람이 가족이 아니었다면, 나는 어떤 거리를 선택할까?",
    source: "notion-guide",
    status: "publish",
    category: "관계",
    topics: ["가족", "거리", "경계", "관계", "자기이해"],
    rationale: "Notion의 대인관계 질문을 하나의 짧은 reflection tool로 전환합니다.",
  },
];
