import type { GuideArticle } from "@/lib/content";

// Initial GUIDE records adapted from the user's Notion counseling guide and Threads archive.
// Threads posts are treated as source notes: repeated ideas are merged into durable website articles
// rather than reproduced post-by-post.
export const sourceDerivedGuides: GuideArticle[] = [
  {
    slug: "how-to-start-therapy",
    category: "상담 시작하기",
    categoryEn: "STARTING THERAPY",
    title: "심리상담, 무엇부터 시작하면 될까요?",
    description: "상담을 알아보기 전 지금의 어려움, 원하는 변화, 현실적인 조건부터 차근차근 정리해봅니다.",
    topics: ["상담 시작", "상담 준비", "상담 목표", "상담 형태"],
    relatedServices: ["individual", "couple", "child-parent", "trauma-attachment"],
    relatedTools: ["therapy-prep-checklist"],
    sourcePlatform: "notion",
    originalUrl: null,
    publishedAt: "2026-08-15",
    updatedAt: "2026-08-15",
    featured: true,
    readTime: "6분",
    intro: "상담이 필요하다는 생각이 들어도 어디서부터 알아봐야 할지는 막막할 수 있습니다. 처음부터 치료기법이나 자격 이름을 모두 알 필요는 없습니다. 먼저 지금 무엇이 힘든지, 상담에서 무엇을 얻고 싶은지, 어떤 조건 안에서 꾸준히 이용할 수 있는지를 정리해보는 것이 시작점이 됩니다.",
    sections: [
      { heading: "먼저 지금의 어려움을 짧게 정리해보세요", paragraphs: ["지금 나를 가장 힘들게 하는 생각, 감정, 사건을 한꺼번에 설명하려 하지 않아도 됩니다. 한두 문장이나 1~3개의 항목으로 적어도 충분합니다.", "언제부터 어려움이 시작되었는지, 그동안 어떤 방식으로 버티거나 해결하려 했는지도 상담의 중요한 단서가 됩니다."] },
      { heading: "상담에서 바라는 변화를 생각해보세요", paragraphs: ["‘문제를 없애고 싶다’는 목표도 괜찮지만 조금 더 생활에 가까운 언어로 바꾸면 상담 방향을 잡기 쉬워집니다. 예를 들어 감정을 덜 억누르고 싶다, 관계에서 내 의견을 말하고 싶다, 불안해도 일상을 유지하고 싶다는 식입니다."] },
      { heading: "나에게 맞는 방식은 사람마다 다릅니다", paragraphs: ["누군가는 생각을 구조화하는 접근이 편하고, 누군가는 감정을 충분히 느끼고 표현하는 과정이 필요합니다. 말로 설명하는 것만으로 부족하다면 신체감각이나 움직임을 함께 살피는 접근을 고려할 수도 있습니다."] },
      { heading: "비용·시간·거리도 치료의 일부입니다", paragraphs: ["좋아 보이는 상담이라도 지속하기 어려운 조건이면 실제 도움으로 이어지기 어렵습니다. 감당할 수 있는 비용과 이동, 일정, 회복에 필요한 에너지를 함께 고려하세요."], note: "상담을 고르는 기준에는 전문성뿐 아니라 내가 실제로 이어갈 수 있는 조건도 포함됩니다." },
    ],
    takeaway: "처음부터 완벽한 상담을 고르기보다, 내가 무엇을 필요로 하는지 조금 더 분명히 아는 것부터 시작해도 됩니다.",
  },
  {
    slug: "when-therapy-feels-uncomfortable",
    category: "상담 잘 이용하기",
    categoryEn: "USING THERAPY WELL",
    title: "상담이 불편하거나 힘들 때 해볼 수 있는 것",
    description: "상담에서 마음에 걸리는 일이 생겼을 때 불편함을 정리하고 관계 안에서 다뤄보는 방법을 살펴봅니다.",
    topics: ["상담 관계", "불편함", "피드백", "경계", "상담 중단"],
    relatedServices: ["individual", "couple", "trauma-attachment"],
    relatedTools: ["therapy-discomfort-note", "between-session-reflection"],
    sourcePlatform: "website",
    originalUrl: null,
    publishedAt: "2026-08-15",
    updatedAt: "2026-08-15",
    featured: true,
    readTime: "7분",
    intro: "상담은 나를 위해 사용하는 시간입니다. 그래서 상담 중 서운함, 불편함, 이해되지 않는 말, 위축되는 느낌이 생겼다면 그 자체가 중요합니다. 모든 불편함이 곧 나쁜 상담이라는 뜻은 아니지만, 그 불편함이 관계 안에서 어떻게 다뤄지는지는 상담의 중요한 일부입니다.",
    sections: [
      { heading: "무엇이 불편했는지 먼저 구체화해보세요", paragraphs: ["‘그냥 별로였다’고 느껴질 수도 있습니다. 가능하다면 어떤 말, 행동, 침묵, 설명, 분위기에서 마음이 걸렸는지 적어보세요. 그 순간의 감정이나 몸의 반응도 함께 살펴볼 수 있습니다."] },
      { heading: "가능하다면 상담 안에서 그대로 말해보세요", paragraphs: ["상담자에게 불편함을 이야기하는 것은 쉽지 않습니다. 그러나 안전한 상담관계라면 이런 피드백 역시 다룰 수 있어야 합니다. ‘지난번에 이런 말을 들었을 때 제가 위축됐어요’처럼 경험을 중심으로 말해볼 수 있습니다."] },
      { heading: "상담자의 반응을 살펴보세요", paragraphs: ["중요한 것은 실수나 오해가 전혀 없는 관계가 아니라, 문제가 생겼을 때 그것을 함께 돌아보고 조정할 수 있는지입니다. 내 경험을 존중하고, 이해하려 하고, 필요하면 설명하거나 수정하려는 반응은 관계를 다시 안전하게 만드는 데 도움이 됩니다."] },
      { heading: "계속 위축된다면 다른 선택도 가능합니다", paragraphs: ["몇 차례 이야기해도 내 경험이 반복해서 무시되거나, 문제를 말할수록 내 탓으로 돌아오거나, 안전하지 않다는 느낌이 커진다면 다른 상담자를 찾는 것을 고려할 수 있습니다."], note: "상담을 중단하거나 상담자를 바꾸는 선택도 상담을 잘 이용하는 방법의 일부입니다." },
    ],
    takeaway: "불편함을 느꼈다는 사실보다, 그 불편함을 관계 안에서 함께 다룰 수 있는지가 더 중요할 수 있습니다.",
  },
  {
    slug: "attachment-is-more-than-a-type",
    category: "마음 이해하기",
    categoryEn: "UNDERSTANDING THE MIND",
    title: "애착은 한 가지 유형으로만 설명되지 않습니다",
    description: "애착을 고정된 성격표처럼 보기보다 가까워짐과 떨어짐, 관계 속 상호작용의 패턴으로 살펴봅니다.",
    topics: ["애착", "안정애착", "불안정애착", "민감성", "관계"],
    relatedServices: ["individual", "couple", "child-parent", "trauma-attachment"],
    relatedTools: ["relationship-distance-question"],
    sourcePlatform: "website",
    originalUrl: null,
    publishedAt: "2026-08-15",
    updatedAt: "2026-08-15",
    featured: true,
    readTime: "7분",
    intro: "애착은 ‘나는 불안형이다’처럼 한 단어로 끝나는 성격 진단이 아닙니다. 관계 속에서 가까워지고, 필요할 때 도움을 구하고, 다시 떨어져 자신의 삶으로 돌아갈 수 있는 움직임 전체를 보는 개념에 가깝습니다.",
    sections: [
      { heading: "좋은 애착은 잘 붙어 있는 것만을 뜻하지 않습니다", paragraphs: ["안정적인 관계에는 가까워짐뿐 아니라 분리와 독립도 포함됩니다. 필요할 때 연결되고, 혼자 해보고 싶을 때는 떨어져 있을 수 있으며, 헤어진 뒤 다시 만날 수 있다는 기대가 유지되는 경험이 중요합니다."] },
      { heading: "애착은 혼자 만드는 것이 아닙니다", paragraphs: ["애착은 관계 안의 상호작용에서 만들어집니다. 특히 아동과 양육자의 관계에서는 성인의 책임이 더 크지만, 아이의 기질과 반응성 역시 상호작용의 모양에 영향을 줍니다."] },
      { heading: "같은 사람도 관계에 따라 다르게 반응할 수 있습니다", paragraphs: ["한 사람에게서는 편안하지만 다른 관계에서는 불안하거나 거리를 두고 싶을 수 있습니다. 그래서 애착 유형 하나로 나와 상대를 모두 설명하려 하면 실제 관계의 맥락을 놓치기 쉽습니다."] },
      { heading: "민감성은 가까이 가는 것과 물러나는 것을 모두 포함합니다", paragraphs: ["상대가 도움이 필요할 때 알아차리고 다가가는 것뿐 아니라, 스스로 해보려 할 때 공간을 내어주는 것도 관계의 민감성에 포함됩니다."] },
    ],
    takeaway: "애착의 목표는 언제나 가까이 있는 것이 아니라, 연결과 독립 사이를 조금 더 유연하게 오갈 수 있는 관계를 만드는 것입니다.",
  },
  {
    slug: "attachment-trauma-differences",
    category: "마음 이해하기",
    categoryEn: "UNDERSTANDING THE MIND",
    title: "애착 트라우마·애착 손상·불안정애착·발달 트라우마는 어떻게 다를까요?",
    description: "서로 겹쳐 보이지만 같은 뜻은 아닌 네 가지 개념을 구분해서 살펴봅니다.",
    topics: ["애착 트라우마", "애착 손상", "불안정애착", "발달 트라우마"],
    relatedServices: ["individual", "couple", "trauma-attachment"],
    relatedTools: [],
    sourcePlatform: "website",
    originalUrl: null,
    publishedAt: "2026-08-15",
    updatedAt: "2026-08-15",
    featured: false,
    readTime: "8분",
    intro: "애착과 트라우마를 설명하는 말들은 온라인에서 자주 섞여 사용됩니다. 하지만 불안정애착, 애착 손상, 애착 트라우마, 발달 트라우마는 출발점과 강조점이 서로 다릅니다. 한 단어로 자신이나 타인을 규정하기보다 어떤 경험과 패턴을 설명하려는 말인지 구분해서 보는 편이 안전합니다.",
    sections: [
      { heading: "불안정애착", paragraphs: ["안정애착 이외의 애착 패턴을 넓게 가리키는 표현입니다. 가까움과 거리, 도움 요청, 분리 상황에서 나타나는 관계 전략을 이해하는 틀이지 그 자체가 곧 트라우마 진단을 뜻하지는 않습니다."] },
      { heading: "애착 손상", paragraphs: ["중요한 관계에서 신뢰와 연결감을 크게 흔드는 사건이나 경험을 설명할 때 사용되는 표현입니다. 특히 커플·부부 치료 맥락에서는 특정 사건 이후 관계의 안전감이 손상된 경험을 다룰 때 쓰입니다."] },
      { heading: "애착 트라우마", paragraphs: ["가까운 대상이 동시에 안전과 공포의 원천이 되는 등 애착 관계 자체에서 심각한 위협과 혼란이 반복되는 경험을 설명할 때 사용됩니다. 모든 불안정애착이나 관계의 상처를 애착 트라우마라고 부르는 것은 지나치게 넓은 사용이 될 수 있습니다."] },
      { heading: "발달 트라우마", paragraphs: ["발달 과정에서 반복되거나 만성적인 위협과 관계 경험이 감정조절, 자기감, 관계, 신체적 반응 등 여러 영역에 광범위하게 영향을 미치는 현상을 설명하는 데 사용됩니다."], note: "이 글은 개념을 구분하기 위한 입문 설명입니다. 진단이나 개인의 경험을 한 범주로 확정하기 위한 자료가 아닙니다." },
    ],
    takeaway: "비슷한 단어라도 같은 경험을 뜻하지 않습니다. 개념보다 먼저 실제로 어떤 경험이 있었고 지금 어떤 영향이 남아 있는지를 살펴보는 것이 중요합니다.",
  },
  {
    slug: "stabilization-does-not-fit-everyone",
    category: "심리치료 알아보기",
    categoryEn: "UNDERSTANDING THERAPY",
    title: "심호흡과 그라운딩이 나에게 안 맞을 수도 있습니다",
    description: "널리 알려진 안정화 방법이 오히려 불편한 사람도 있는 이유와 대안을 살펴봅니다.",
    topics: ["안정화", "그라운딩", "호흡", "트라우마", "신체감각"],
    relatedServices: ["individual", "trauma-attachment"],
    relatedTools: ["emotion-check-in", "stress-response-map", "one-bite-regulation", "safe-place-builder"],
    sourcePlatform: "website",
    originalUrl: null,
    publishedAt: "2026-08-15",
    updatedAt: "2026-08-15",
    featured: false,
    readTime: "7분",
    intro: "불안하거나 힘들 때 심호흡, 그라운딩, 나비포옹 같은 방법을 권유받곤 합니다. 많은 사람에게 도움이 될 수 있지만 모두에게 같은 방식으로 편안한 것은 아닙니다. 특히 몸의 감각이나 안정되는 경험 자체가 낯선 사람에게는 ‘편안해져야 한다’는 시도가 오히려 부담이 될 수도 있습니다.",
    sections: [
      { heading: "기법이 안 맞는다고 내가 잘못된 것은 아닙니다", paragraphs: ["안정화 기법은 목적이 아니라 도구입니다. 한 가지 방법에서 편안함을 느끼지 못했다면 실패한 것이 아니라 내 신경계와 상황에 다른 접근이 필요하다는 정보일 수 있습니다."] },
      { heading: "몸 안쪽보다 바깥쪽이 쉬울 수도 있습니다", paragraphs: ["호흡이나 심장박동에 집중하면 오히려 불안이 커지는 사람도 있습니다. 그럴 때는 눈을 뜨고 주변의 색이나 사물을 찾거나, 발이 닿는 바닥처럼 비교적 중립적인 감각부터 확인할 수 있습니다."] },
      { heading: "아주 작은 편안함부터 찾습니다", paragraphs: ["완전히 안전하거나 편안한 상태를 만들려 하지 않아도 됩니다. 덜 불편한 곳, 조금 중립적인 감각, 잠깐 숨을 돌릴 수 있는 순간을 찾는 것부터 시작할 수 있습니다."] },
      { heading: "힘든 경험은 감당할 수 있는 만큼만", paragraphs: ["트라우마 치료에서는 힘든 경험에 오래 머무는 것보다 괜찮은 상태와 오가고, 감당 가능한 크기로 나누어 접근하는 방식을 사용하기도 합니다."] },
    ],
    takeaway: "좋은 안정화는 정해진 기법을 잘 수행하는 것이 아니라, 내 몸과 마음이 실제로 조금 덜 압도되는 방법을 찾아가는 과정입니다.",
  },
  {
    slug: "online-therapy-tips",
    category: "상담 잘 이용하기",
    categoryEn: "USING THERAPY WELL",
    title: "비대면 상담을 더 잘 이용하는 방법",
    description: "화상·전화·채팅상담의 차이를 알고 상담에 집중할 수 있는 환경을 준비해봅니다.",
    topics: ["비대면 상담", "화상상담", "전화상담", "채팅상담"],
    relatedServices: ["individual", "couple"],
    relatedTools: ["between-session-reflection"],
    sourcePlatform: "notion",
    originalUrl: null,
    publishedAt: "2026-08-15",
    updatedAt: "2026-08-15",
    featured: false,
    readTime: "5분",
    intro: "비대면 상담은 이동 부담을 줄이고 익숙한 공간에서 참여할 수 있다는 장점이 있습니다. 반면 상담에 들어가기 전 마음을 전환할 시간이 짧고, 사용하는 매체에 따라 경험도 달라질 수 있습니다.",
    sections: [
      { heading: "화상상담", paragraphs: ["상담 시작 직전에 링크만 켜기보다 2~3분 정도 화면 앞에 앉아 마음을 정리해보세요. 혼자 이야기할 수 있는 공간인지, 이어폰과 네트워크 상태는 괜찮은지, 연결이 끊기면 어떻게 연락할지도 확인하면 좋습니다."] },
      { heading: "전화상담", paragraphs: ["얼굴이 보이지 않아 평소보다 빠르게 많은 이야기를 쏟아내는 경험이 생길 수 있습니다. 중간중간 속도와 호흡, 몸의 긴장을 확인해보세요."] },
      { heading: "채팅상담", paragraphs: ["말보다 전달되는 정보량이 제한될 수 있습니다. 꼭 다루고 싶은 상황이나 문장이 있다면 미리 메모해두고 필요한 부분을 붙여넣는 방식도 도움이 됩니다."] },
      { heading: "상담 후 전환 시간도 남겨두세요", paragraphs: ["집이나 직장에서 바로 상담을 시작하고 끝낼 수 있다는 편리함 때문에 종료 직후 곧바로 일상 업무로 돌아가게 되기 쉽습니다. 가능하다면 몇 분이라도 정리하고 쉬는 시간을 확보하세요."] },
    ],
    takeaway: "비대면 상담에서도 상담 전후의 작은 전환 시간을 의도적으로 만드는 것이 도움이 됩니다.",
  },
  {
    slug: "child-centered-limit-setting",
    category: "마음 이해하기",
    categoryEn: "UNDERSTANDING THE MIND",
    title: "아이의 감정은 인정하고 한계는 분명하게: ACT 제한설정",
    description: "아동중심 놀이치료에서 사용하는 제한설정의 핵심을 일상 양육 언어로 살펴봅니다.",
    topics: ["놀이치료", "양육", "제한설정", "감정 인정", "대안 행동"],
    relatedServices: ["child-parent"],
    relatedTools: [],
    sourcePlatform: "website",
    originalUrl: null,
    publishedAt: "2026-08-15",
    updatedAt: "2026-08-15",
    featured: false,
    readTime: "6분",
    intro: "아이의 감정을 존중한다는 것은 모든 행동을 허용한다는 뜻이 아닙니다. 아동중심 놀이치료의 제한설정에서는 감정과 욕구는 인정하되, 안전과 관계를 위해 필요한 한계를 분명히 하고 가능한 대안을 함께 제시합니다.",
    sections: [
      { heading: "A — 감정과 욕구를 인정하기", paragraphs: ["먼저 아이가 무엇을 원하고 어떤 감정을 느끼는지 말로 담아줍니다. ‘정말 더 하고 싶구나’, ‘화가 많이 났구나’처럼 아이의 경험을 인정합니다."] },
      { heading: "C — 한계를 분명하게 전달하기", paragraphs: ["허용할 수 없는 행동은 짧고 명확하게 알려줍니다. 핵심은 아이의 감정을 막는 것이 아니라 자신이나 다른 사람에게 해가 되는 행동, 관계를 해치는 행동에 경계를 세우는 것입니다."] },
      { heading: "T — 가능한 대안을 제시하기", paragraphs: ["안 되는 행동만 멈추라고 하기보다 같은 욕구를 더 안전하게 표현할 방법을 제안합니다. 아이가 선택할 수 있는 대안을 주는 것이 중요합니다."] },
      { heading: "완벽하게 할 필요는 없습니다", paragraphs: ["부모도 지치고 감정이 흔들릴 수 있습니다. 제한설정이 잘 되지 않은 순간이 있었다면 다시 돌아와 감정과 한계, 대안을 차근차근 이어가면 됩니다."], note: "여기서 ACT는 수용전념치료(Acceptance and Commitment Therapy)가 아니라 제한설정의 Acknowledge–Communicate–Target 모델을 뜻합니다." },
    ],
    takeaway: "감정은 받아주고, 안전을 위한 한계는 분명하게, 행동에는 가능한 대안을 제시하는 것이 핵심입니다.",
  },
];
