import type { ToolItem } from "@/lib/tools";

export const sourceDerivedTools: ToolItem[] = [
  {
    title: "첫 상담 준비 체크리스트",
    slug: "therapy-prep-checklist",
    description: "상담을 시작하기 전 지금의 어려움, 원하는 변화, 나에게 맞는 상담 방식과 현실적인 조건을 정리해봅니다.",
    category: "상담",
    topics: ["첫 상담", "상담 준비", "목표", "상담 스타일"],
    format: "체크리스트",
    relatedGuides: ["before-your-first-session", "choosing-a-therapist"],
    relatedServices: ["individual", "couple", "child-parent", "trauma-attachment"],
    publishedAt: "2026-08-15",
    updatedAt: "2026-08-15",
    featured: true,
    sections: [
      { heading: "지금의 나", prompts: ["지금 나를 가장 힘들게 하는 생각·감정·사건을 1~3가지 적어보세요.", "언제부터였는지, 지금까지 어떤 방식으로 버텨오거나 대처해왔는지 적어보세요."] },
      { heading: "상담에서 바라는 것", prompts: ["상담을 통해 달라졌으면 하는 것은 무엇인가요?", "지지적·정리형·조언형·공감형·직면형 중 어떤 방식의 도움에 더 마음이 가나요?"] },
      { heading: "현실적인 조건", prompts: ["내가 감당할 수 있는 비용·시간·이동거리·에너지는 어느 정도인가요?", "상담을 일정 기간 이어가기 위해 미리 조정해야 할 일이 있나요?"] },
    ],
  },
  {
    title: "상담에서 불편했던 순간 정리하기",
    slug: "therapy-discomfort-note",
    description: "상담에서 마음에 걸렸던 지점을 정리하고, 그것을 관계 안에서 어떻게 다뤄볼지 준비하는 기록지입니다.",
    category: "상담",
    topics: ["상담 관계", "불편함", "피드백", "경계"],
    format: "기록지",
    relatedGuides: ["is-therapy-working"],
    relatedServices: ["individual", "couple", "trauma-attachment"],
    publishedAt: "2026-08-15",
    updatedAt: "2026-08-15",
    featured: true,
    sections: [
      { heading: "무엇이 불편했나요?", prompts: ["마음에 걸린 말·행동·침묵·상황은 무엇이었나요?", "그 순간 어떤 감정과 몸의 반응이 있었나요?", "내가 기대했던 것과 실제 경험의 차이는 무엇이었나요?"] },
      { heading: "상담 안에서 말해보기", prompts: ["다음 상담에서 그대로 말한다면 어떤 문장으로 시작할 수 있을까요?", "내가 이 이야기를 꺼냈을 때 상담자에게 기대하는 반응은 무엇인가요?"] },
    ],
  },
  {
    title: "정보를 찾을수록 불안해질 때 중심 잡기",
    slug: "information-anxiety-reset",
    description: "검색과 알고리즘을 따라갈수록 불안이 커질 때, 정보 탐색과 감정 조절을 잠시 분리해보는 도구입니다.",
    category: "자기돌봄",
    topics: ["불안", "정보 과부하", "알고리즘", "중심잡기"],
    format: "가이드",
    relatedGuides: [],
    relatedServices: ["individual"],
    publishedAt: "2026-08-15",
    updatedAt: "2026-08-15",
    featured: false,
    sections: [
      { heading: "먼저 확인하기", prompts: ["지금 나는 정보를 얻고 싶은가요, 불안을 줄이고 싶은가요?", "같은 정보를 반복해서 확인하고 있지는 않나요?"] },
      { heading: "능동적으로 탐색하기", prompts: ["알고리즘 추천이 아니라 내가 직접 검색어를 정해보세요.", "반대 관점이나 다른 출처도 하나씩 확인해보세요."] },
      { heading: "멈출 시점", prompts: ["더 찾아볼수록 혼란과 불안이 커진다면 지금은 검색을 멈춰도 됩니다.", "믿을 만한 사람과 전혀 다른 이야기를 나누거나 몸을 움직인 뒤 다시 판단해보세요."] },
    ],
  },
  {
    title: "힘든 감정을 한입거리로 다루기",
    slug: "one-bite-regulation",
    description: "힘든 경험에 오래 머물기보다 괜찮은 상태와 오가며, 지금 감당할 수 있는 만큼만 다뤄봅니다.",
    category: "자기돌봄",
    topics: ["감정", "트라우마", "펜듈레이션", "타이테이션", "자기조절"],
    format: "연습",
    relatedGuides: ["body-remembers"],
    relatedServices: ["individual", "trauma-attachment"],
    publishedAt: "2026-08-15",
    updatedAt: "2026-08-15",
    featured: true,
    sections: [
      { heading: "괜찮은 쪽을 먼저 찾기", prompts: ["지금 몸이나 마음에서 비교적 괜찮은 부분은 어디인가요?", "편안함·안전함·중립적인 감각 중 아주 작은 것 하나를 찾아보세요."] },
      { heading: "한입만", prompts: ["힘든 감정이나 장면을 아주 조금만 떠올린다면 어느 정도가 감당 가능한가요?", "강도가 올라가면 다시 괜찮은 감각이나 주변 환경으로 주의를 옮겨보세요."] },
      { heading: "끝내기", prompts: ["오늘은 여기까지만 해도 충분한 지점을 정해보세요.", "끝난 뒤 지금의 몸이 무엇을 필요로 하는지 확인해보세요."] },
    ],
  },
  {
    title: "나만의 안식처 이미지 만들기",
    slug: "safe-place-builder",
    description: "보았을 때 미소가 나거나 조금 편안해지는 장면을 감각적으로 구성해 나만의 자원 이미지를 만듭니다.",
    category: "자기돌봄",
    topics: ["안식처", "이미지", "감각", "안정화", "자원"],
    format: "시각화",
    relatedGuides: ["body-remembers"],
    relatedServices: ["individual", "trauma-attachment"],
    publishedAt: "2026-08-15",
    updatedAt: "2026-08-15",
    featured: false,
    sections: [
      { heading: "장면 만들기", prompts: ["어디에 있으면 조금 편안해질까요? 실제 장소여도, 상상 속 장소여도 됩니다.", "빛·온도·소리·냄새·촉감은 어떤가요?", "사람이나 동물이 있다면 누구이며, 없다면 비어 있어도 좋습니다."] },
      { heading: "내 몸의 반응 확인하기", prompts: ["그 장면을 떠올렸을 때 몸에서 아주 조금이라도 편해지는 곳이 있나요?", "오히려 불편해진다면 억지로 유지하지 말고 눈을 뜨고 주변의 실제 공간을 확인하세요."] },
    ],
  },
  {
    title: "가족과의 거리 다시 생각하기",
    slug: "relationship-distance-question",
    description: "가족이라는 역할을 잠시 내려놓고, 나에게 필요한 관계의 거리를 다시 생각해보는 짧은 질문입니다.",
    category: "관계",
    topics: ["가족", "거리", "경계", "관계", "자기이해"],
    format: "리플렉션",
    relatedGuides: [],
    relatedServices: ["individual", "couple"],
    publishedAt: "2026-08-15",
    updatedAt: "2026-08-15",
    featured: false,
    sections: [
      { heading: "한 가지 질문", prompts: ["이 사람이 가족이 아니었다면, 나는 이 사람과 어느 정도 거리에서 지내고 싶을까요?", "지금 유지하는 거리와 내가 원하는 거리 사이에는 어떤 차이가 있나요?", "그 차이를 줄이기 위해 내가 할 수 있는 가장 작은 선택은 무엇인가요?"] },
    ],
  },
];
